obc_img = {
    '000': 'https://i.imgur.com/hDI37FB.png',
    '001': 'https://i.imgur.com/UPLvY9X.png',
    '010': 'https://i.imgur.com/mJMa2L3.png',
    '100': 'https://i.imgur.com/H1zBoJ7.png',
    '011': 'https://i.imgur.com/67TIglP.png',
    '101': 'https://i.imgur.com/KmhskOq.png',
    '110': 'https://i.imgur.com/5unj2l8.png',
    '111': 'https://i.imgur.com/fbZnSUy.png'
}

team_colors = {
    "ARI": '005F61',
    "ATL": 'CE1141',
    "BAL": 'DF4601',
    "BOS": 'BD3039',
    "CHC": '0E3386',
    "CIN": 'C6011F',
    "CLE": '0C2340',
    "COL": '33006F',
    "CWS": '27251F',
    "DET": 'FA4616',
    "HOU": 'F4911E',
    "KCR": '004687',
    "LAA": 'BA0021',
    "LA": '005A9C',
    "MIA": '00A3E0',
    "MIL": 'FFC52F',
    "MIN": 'D31145',
    "WSH": '67ABE5',
    "NYM": 'FF5910',
    "NYY": '0C2340',
    "OAK": '003831',
    "PHI": '6F263D',
    "PIT": 'FDB827',
    "SDP": 'AE8F6F',
    "SEA": '005C5C',
    "SFG": 'FD5A1E',
    "STL": 'C41E3A',
    "TB": '8FBCE6',
    "TEX": '003278',
    "TOR": '134A8E'
}

team_logos = {
    "ARI": 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Arizona_Diamondbacks_logo.svg/1200px-Arizona_Diamondbacks_logo.svg.png',
    "ATL": 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Atlanta_Braves_Insignia.svg/1200px-Atlanta_Braves_Insignia.svg.png',
    "BAL": 'https://upload.wikimedia.org/wikipedia/en/thumb/7/75/Baltimore_Orioles_cap.svg/1200px-Baltimore_Orioles_cap.svg.png',
    "BOS": 'https://upload.wikimedia.org/wikipedia/en/thumb/6/6d/RedSoxPrimary_HangingSocks.svg/1200px-RedSoxPrimary_HangingSocks.svg.png',
    "CHC": 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Chicago_Cubs_logo.svg/1200px-Chicago_Cubs_logo.svg.png',
    "CIN": 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Cincinnati_Reds_Logo.svg/1280px-Cincinnati_Reds_Logo.svg.png',
    "CLE": 'https://media.discordapp.net/attachments/545326310742949910/782810237882073179/fakeGuardiansLogo.png',
    "COL": 'https://i.imgur.com/vRLVXVv.png',
    "CWS": 'https://i.imgur.com/fcnJsKf.png',
    "DET": 'https://i.imgur.com/xcNTjSF.png',
    "HOU": 'https://i.imgur.com/e6aDFww.png',
    "KCR": 'https://i.imgur.com/MeufMho.png',
    "LAA": 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Los_Angeles_Angels_of_Anaheim.svg/1200px-Los_Angeles_Angels_of_Anaheim.svg.png',
    "LA": 'https://i.imgur.com/hFlRHwB.png',
    "MIA": 'https://i.imgur.com/5ydtaiX.png',
    "MIL": 'https://i.imgur.com/ygjBq93.png',
    "MIN": 'https://i.imgur.com/NE2RAm6.png',
    "WSH": 'https://media.discordapp.net/attachments/344862539240308736/784650866039980072/image0.png?width=610&height=610',
    "NYM": 'https://i.imgur.com/ixq5TmD.png',
    "NYY": 'https://i.imgur.com/GI4skuf.png',
    "OAK": 'https://i.imgur.com/5jasK2K.png',
    "PHI": 'https://i.imgur.com/9k4Fc73.png',
    "PIT": 'https://i.imgur.com/L68YhLT.png',
    "SDP": 'https://i.imgur.com/7zu30lL.png',
    "SEA": 'https://i.imgur.com/ImngzeS.png',
    "SFG": 'https://i.imgur.com/cbYhBu3.png',
    "STL": 'https://i.imgur.com/1DQ3DQi.png',
    "TB": 'https://i.imgur.com/lma9b09.png',
    "TEX": 'https://i.imgur.com/jtwUeNL.png',
    "TOR": 'https://i.imgur.com/DaGMIWl.png'
}